# docker-compose.yml
version: "3.8"

services:
  backend:
    build: .
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-4000}
      - MONGO_URI=mongodb://mongodb:27017/
      - JWT_SECRET=${JWT_SECRET:-thisismy__________________jwtSECRET789456123}
      - ACCESS_TOKEN_EXPIRE=${ACCESS_TOKEN_EXPIRE:-15m}
      - REFRESH_JWT_SECRET=${REFRESH_JWT_SECRET:-thisismy__________________refreshSECRET789456123}
      - REFRESH_TOKEN_EXPIRE=${REFRESH_TOKEN_EXPIRE:-7d}
    depends_on:
      - mongodb
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
