version: "3.8"

services:
  backend:
    build: .
    restart: always
    env_file: .env
    ports:
      - "80:4000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - uploads:/usr/src/app/uploads
    networks:
      - app-network

  mongodb:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:
  uploads:

networks:
  app-network:
    driver: bridge